// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHzIikw4LQo4Y2dYFiBw1kgyTJjMF45Wo',
    appId: '1:887150380409:web:ebdc30740077ce8fd75ba8',
    messagingSenderId: '887150380409',
    projectId: 'cst-pratap-demo',
    authDomain: 'cst-pratap-demo.firebaseapp.com',
    storageBucket: 'cst-pratap-demo.firebasestorage.app',
    measurementId: 'G-G2F0R6C42J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASdzUm5g8ov_kCkS-Lv7PupcyBfztjuPY',
    appId: '1:887150380409:android:7122e9df75a3ce4ad75ba8',
    messagingSenderId: '887150380409',
    projectId: 'cst-pratap-demo',
    storageBucket: 'cst-pratap-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV_EadimflgoQ4bnlR-f5Gu5yngiqXL98',
    appId: '1:887150380409:ios:60bf0d4bd2552adfd75ba8',
    messagingSenderId: '887150380409',
    projectId: 'cst-pratap-demo',
    storageBucket: 'cst-pratap-demo.firebasestorage.app',
    iosBundleId: 'com.example.idealCst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV_EadimflgoQ4bnlR-f5Gu5yngiqXL98',
    appId: '1:887150380409:ios:60bf0d4bd2552adfd75ba8',
    messagingSenderId: '887150380409',
    projectId: 'cst-pratap-demo',
    storageBucket: 'cst-pratap-demo.firebasestorage.app',
    iosBundleId: 'com.example.idealCst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHzIikw4LQo4Y2dYFiBw1kgyTJjMF45Wo',
    appId: '1:887150380409:web:5a6bbdfee8674d1fd75ba8',
    messagingSenderId: '887150380409',
    projectId: 'cst-pratap-demo',
    authDomain: 'cst-pratap-demo.firebaseapp.com',
    storageBucket: 'cst-pratap-demo.firebasestorage.app',
    measurementId: 'G-HJ2C7HD88Z',
  );
}
